import Link from "next/link";
import type {
  MemoData,
  LocationChapter,
  DemographicChapter,
  MarketChapter,
  SwotChapter,
  ScoreChapter,
} from "@/types/memo";
import MemoScore from "@/components/MemoScore";
import ChapterSection from "@/components/ChapterSection";
import SwotGrid from "@/components/SwotGrid";

interface MemoDisplayProps {
  memo: MemoData;
  locationChapter: LocationChapter;
  demographicChapter: DemographicChapter;
  marketChapter: MarketChapter;
  swotChapter: SwotChapter;
  scoreChapter: ScoreChapter;
}

export default function MemoDisplay({
  memo,
  locationChapter,
  demographicChapter,
  marketChapter,
  swotChapter,
  scoreChapter,
}: MemoDisplayProps) {
  const date = new Date(memo.createdAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="max-w-3xl mx-auto px-4 py-8">
      {/* Header */}
      <div className="bg-navy text-white rounded-xl px-8 py-7 mb-8">
        <p className="text-xs uppercase tracking-widest text-blue-300 font-sans mb-2">
          Investment Memorandum
        </p>
        <h1 className="text-2xl font-bold font-sans leading-snug">
          {memo.address}
        </h1>
        <p className="text-sm text-blue-200 font-sans mt-2">{date}</p>
      </div>

      {/* Score */}
      <MemoScore
        overallScore={memo.overallScore}
        locationScore={memo.locationScore}
        demographicScore={memo.demographicScore}
        marketScore={memo.marketScore}
        riskScore={memo.riskScore}
      />

      {/* Chapters */}
      <div className="bg-white rounded-xl border border-gray-200 px-8 py-8 mb-8">
        <ChapterSection
          title="Location Overview"
          data={locationChapter as unknown as Record<string, string | string[]>}
        />
        <ChapterSection
          title="Demographic Analysis"
          data={demographicChapter as unknown as Record<string, string | string[]>}
        />
        <ChapterSection
          title="Market Landscape"
          data={marketChapter as unknown as Record<string, string | string[]>}
        />
      </div>

      {/* SWOT */}
      <div className="bg-white rounded-xl border border-gray-200 px-8 py-8 mb-8">
        <SwotGrid swot={swotChapter} />
      </div>

      {/* Executive Summary */}
      <div className="bg-white rounded-xl border border-gray-200 px-8 py-8 mb-8">
        <section className="mb-6">
          <h2 className="text-lg font-bold text-navy font-sans uppercase tracking-widest mb-4 pb-2 border-b border-gray-200">
            Executive Summary
          </h2>
          <p className="font-serif text-gray-800 text-base leading-relaxed">
            {scoreChapter.executiveSummary}
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-lg font-bold text-navy font-sans uppercase tracking-widest mb-4 pb-2 border-b border-gray-200">
            Key Takeaways
          </h2>
          <ul className="list-disc list-inside font-serif text-gray-800 text-base leading-relaxed space-y-2">
            {scoreChapter.keyTakeaways.map((item, i) => (
              <li key={i}>{item}</li>
            ))}
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-navy font-sans uppercase tracking-widest mb-4 pb-2 border-b border-gray-200">
            Recommendation
          </h2>
          <p className="font-serif text-gray-800 text-base leading-relaxed">
            {scoreChapter.recommendation}
          </p>
        </section>
      </div>

      {/* Footer */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-2 pb-8">
        <p className="text-xs text-gray-400 font-sans text-center sm:text-left">
          Generated by AI. This is not financial advice.
        </p>
        <Link
          href="/"
          className="px-5 py-2.5 bg-accent-blue text-white text-sm font-medium rounded-lg hover:bg-blue-700 transition-colors duration-150 font-sans"
        >
          Generate New Memo
        </Link>
      </div>
    </div>
  );
}
